CREATE DATABASE Inventory_Management

USE Inventory_Management

-- Create custmer table
CREATE TABLE Customer
(
	Customer_ID INT NOT NULL IDENTITY(1,1),
	FName VARCHAR(30) NOT NULL,
	LName VARCHAR(30) NOT NULL,
	MName VARCHAR(30),
	Phone VARCHAR(15) NOT NULL UNIQUE,
	Cust_Address VARCHAR(100) NOT NULL,
	PRIMARY KEY(Customer_ID)
)

-- Create product table
CREATE TABLE Product
(
	Product_ID INT IDENTITY(1,1) NOT NULL,
	Product_Name VARCHAR(30) NOT NULL,
	Price MONEY NOT NULL,
	Prod_Description VARCHAR(180) NOT NULL,
	PRIMARY KEY(Product_ID)
)

-- Create supplier table
CREATE TABLE Supplier
(
	Supplier_ID INT NOT NULL IDENTITY(1,1),
	FName VARCHAR(30) NOT NULL,
	LName VARCHAR(30) NOT NULL,
	MName VARCHAR(30),
	Phone VARCHAR(15) NOT NULL UNIQUE,
	Supplier_Address VARCHAR(100) NOT NULL,
	PRIMARY KEY(Supplier_ID)
)

-- Create WAREHOUSE TABLE
CREATE TABLE Warehouse
(
	WarehouseID INT NOT NULL IDENTITY(1,1),
	Name VARCHAR(30) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	PRIMARY KEY(WarehouseID)
)
--Create Item table
CREATE TABLE Item
(
	ItemID INT NOT NULL IDENTITY(1,1),
	Name VARCHAR(30) NOT NULL,
	Price MONEY NOT NULL,
	Description VARCHAR(180) NOT NULL,
	PRIMARY KEY(ItemID)
)

-- Create Order table
CREATE TABLE OrderT
(
	Order_ID INT NOT NULL IDENTITY(1,1),
	Customer_ID INT NOT NULL,
	Order_Date DATE DEFAULT GETDATE(), -- Current date
	FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Order_ID)
)

-- Create Order Line table
CREATE TABLE Order_Line
(
	Order_ID INT NOT NULL,
	Product_ID INT NOT NULL,
	Amount INT NOT NULL,
	Delivary_Date DATE NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY(Order_ID) REFERENCES OrderT(Order_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Product_ID) REFERENCES Product(Product_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Order_ID,Product_ID)
)

-- create Assembly table
CREATE TABLE AssemblyT
(
	Product_ID INT NOT NULL,
	Item_ID INT NOT NULL,
	Amount INT NOT NULL,
	FOREIGN KEY(Product_ID) REFERENCES Product(Product_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Item_ID) REFERENCES Item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
)
ALTER TABLE AssemblyT
ADD CONSTRAINT PK_ASS PRIMARY KEY(Product_ID,Item_ID)

-- Create Location Table
CREATE TABLE LocationT
(
	Warehouse_ID INT NOT NULL,
	Product_ID INT NOT NULL,
	Quantity INT NOT NULL,
	FOREIGN KEY(Warehouse_ID) REFERENCES Warehouse(WarehouseID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Product_ID) REFERENCES Product(Product_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Warehouse_ID,Product_ID)
)

--CREATE stock table
CREATE TABLE Stock
(
	Warehouse_ID INT NOT NULL,
	Item_ID INT NOT NULL,
	Quantity INT NOT NULL,
	FOREIGN KEY (Warehouse_ID) REFERENCES Warehouse(WarehouseID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Item_ID) REFERENCES Item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Warehouse_ID,Item_ID)
)
--	create employee table
CREATE TABLE Employee
(
	Employee_ID INT NOT NULL IDENTITY(1,1),
	FName VARCHAR(30) NOT NULL,
	LName VARCHAR(30) NOT NULL,
	MName VARCHAR(30),
	Phone_Number VARCHAR(15) NOT NULL UNIQUE,
	EMail VARCHAR(30) NOT NULL UNIQUE,
	User_Name VARCHAR(30) NOT NULL UNIQUE,
	Password VARCHAR(30) NOT NULL,
	PRIMARY KEY(Employee_ID)
)

--Create supply table 
CREATE TABLE Supply
(
	Supplier_ID INT NOT NULL,
	Item_ID INT NOT NULL,
	Employee_ID INT NOT NULL,
	Supply_Date DATE NOT NULL DEFAULT GETDATE(),
	Amount INT NOT NULL,
	FOREIGN KEY(Supplier_ID) REFERENCES Supplier(Supplier_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Item_ID) REFERENCES Item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Employee_ID) REFERENCES Employee(Employee_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Supplier_ID,Item_ID,Employee_ID)
)